version: '3.7'

services:
  sonarqube-db:
    image: postgres:12
    networks:
      - my-network
    env_file:
      - sonar-secrets.env
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager

  sonarqube:
    image: sonarqube:latest
    networks:
      - my-network
    ports:
      - "9000:9000"
    env_file:
      - sonar-secrets.env    
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  my-network:

volumes:
  sonarqube-db-data:
  sonarqube-data:

