version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - nextcloud_secrets.env
  app:
    image: nextcloud:latest
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    env_file:
      - nextcloud_secrets.env
    ports: 
      - 8080:80

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8888:80
    depends_on:
      - app

volumes:
  db_data:
  nextcloud:

